service: step-function
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  architecture: x86_64
  stage: ${opt:stage, 'dev'}
  region: us-east-1

plugins:
  - serverless-cloudformation-sub-variables
  - serverless-parameters
  - serverless-step-functions

custom:
  parameters:
    DynamoTableName:
      Type: String
      Default: ${param:DynamoTableName}
    DynamoTableArn:
      Type: String
      Default: ${param:DynamoTableArn}
    DynamoSubscriberTableName:
      Type: String
      Default: ${param:DynamoSubscriberTableName}
    DynamoSubscriberTableArn:
      Type: String
      Default: ${param:DynamoSubscriberTableArn}
    SNSTopicName:
      Type: String
      Default: ${param:SNSTopicName}
    SNSTopicARN:
      Type: String
      Default: ${param:SNSTopicARN}

resources:
  Resources:
    ReminderStepFunction:
      Type: AWS::StepFunctions::StateMachine
      Properties:
        StateMachineName: ${sls:stage}-ReminderStepFxn
        StateMachineType: "STANDARD"
        RoleArn: arn:aws:iam::164593963429:role/TestStepFnRole
        DefinitionSubstitutions:
          DynamoDbTableName: "#{DynamoTableName}"
          SNSArn: "#{SNSTopicARN}"
        DefinitionString: |-
         ${file(./importDefinition.js):definition}

    StepFxnRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: ${sls:stage}-Remind-Steps-Role-1
        Description: "Role for Step function to execute flow"
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement: 
            - Effect: Allow
              Principal:
                Service: 
                  - "states.amazonaws.com"
              Action: 
                - "sts:AssumeRole"
        Policies:
          - PolicyName: ${sls:stage}-Remind-Steps-Role-1-Policies
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action: 
                    - "dynamodb:DeleteItem"
                    - "sns:Publish"
                  Resource:
                    - "#{SNSTopicARN}"
                    - "#{DynamoTableArn}"
  # Outputs for other modules
  Outputs:
    StepFxnName:
      Description: Name of step function
      Value:
        Fn::GetAtt:
          - ReminderStepFunction
          - Name
    StepFxnArn:
      Description: Arn of step function
      Value:
        Ref: ReminderStepFunction