service: backend-resources
frameworkVersion: '3'
useDotEvn: true

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: us-east-1

plugins:
  - serverless-cloudformation-sub-variables

# Create DynamoDb Table and SNS Topics
resources:
  Resources:
    # Reminder table stores the reminders as history
    ReminderTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${sls:stage}-Reminders
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: "S"
          - AttributeName: messageid
            AttributeType: "S"
          - AttributeName: timestamp
            AttributeType: "N"
        KeySchema: 
          - AttributeName: messageid
            KeyType: HASH
          - AttributeName: timestamp
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: EmailIndexView
            KeySchema:
              - AttributeName: email
                KeyType: HASH
              - AttributeName: timestamp
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        BillingMode: PROVISIONED 
        ProvisionedThroughput:
           ReadCapacityUnits: 1
           WriteCapacityUnits: 1
    # For each user identified by email, we store the SNS subscription Arn
    ReminderSubscriberTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${sls:stage}-ReminderTopicSubscribers
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: "S"
        KeySchema: 
          - AttributeName: email
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST 
    ReminderTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${self:provider.stage}-Reminders
  # Outputs for other modules
  Outputs:
    DynamoTableName:
      Description: Name of DynamoTable
      Value: 
        Ref: ReminderTable
    DynamoTableArn:
      Description: Arn of table created
      Value:
        Fn::GetAtt:
          - ReminderTable
          - Arn
    DynamoSubscriberTableName:
      Description: Name of Subscriber DynamoTable
      Value: 
        Ref: ReminderSubscriberTable
    DynamoSubscriberTableArn:
      Description: Arn of Subscriber table created
      Value:
        Fn::GetAtt:
          - ReminderSubscriberTable
          - Arn
    SNSTopicName:
      Description: Name of SNS Topic
      Value: 
        Fn::GetAtt: 
          - ReminderTopic
          - TopicName
    SNSTopicARN:
      Description: ARN of SNS Topic
      Value: 
        Ref: ReminderTopic